baseURL: 'https://upthe.town/'
title: 'Up The Town'
theme: 'utst'

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1

  cy:
    languageName: Cymraeg
    weight: 2

taxonomies:
  tag: tags
  media: media
  person: people
  player: players
  match: matches
  season: seasons
